# Generated by Django 5.1.6 on 2025-03-05 19:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "date_published",
                    models.DateField(
                        auto_now_add=True, verbose_name="Publication Date"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Short introduction to the article",
                        max_length=250,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("text", 0), ("image", 1), ("quote", 2), ("link", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 0), ("author", 0)]],
                                {},
                            ),
                            3: ("wagtail.blocks.URLBlock", (), {}),
                        },
                    ),
                ),
                (
                    "thumbnail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
            bases=("wagtailcore.page",),
        ),
    ]
